package br.com.ssapg_project_v0_0;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class A extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,23","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public A() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1349px");
		mainLayout.setHeight("600px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("1349px");
		setHeight("600px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("80px");
		label_1.setHeight("-1px");
		label_1.setValue("Aluno");
		mainLayout.addComponent(label_1);
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setImmediate(false);
		textField_2.setWidth("100.0%");
		textField_2.setHeight("-1px");
		textField_2.setSecret(false);
		mainLayout.addComponent(textField_2);
		mainLayout.setExpandRatio(textField_2, 1.0f);
		
		return mainLayout;
	}

}
